### PR TITLE
Switch to gh actions

### PR DESCRIPTION
**Pull request by SchoolGuy**
Travis is not the way we go inside Cobbler anymore, thus remove it and replace it with GH Actions.

### CODE REVIEW

**Comment by SchoolGuy** [comment]
Okay so libvirt-dev can't be found. This is very strange since this package is existing. I'll try to rerun later.

**Comment by SchoolGuy** [comment]
So this works locally in a Docker container. I meanwhile researched that libvirt is not possible inside GH Actions.

**Comment by SchoolGuy** [comment]
Here is the issue which tells us that this is not possible - https://github.com/actions/virtual-environments/issues/183

**Review by meaksh — APPROVED** [review]
LGTM :+1:

**Pull request merged**
