### PR TITLE
Remove ethtool and Python 2 code

### LINKED ISSUE #66: ethtool: installation error with pip
I tried to install Koan in a new virtualenv with pip an got the following error:

```bash
$ pip install .
Processing /home/dom/git/work/koan
Collecting simplejson 
  Using cached simplejson-3.17.2-cp38-cp38-manylinux2010_x86_64.whl (137 kB)
Collecting ethtool 
  Using cached ethtool-0.14.tar.gz (43 kB)
Collecting distro
Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB) 
Collecting libvirt-python                                                              
  Downloading libvirt-python-6.7.0.tar.gz (208 kB)
     |████████████████████████████████| 208 kB 1.9 MB/s 
Collecting netifaces
  Using cached netifaces-0.10.9.tar.gz (28 kB)
Building wheels for collected packages: koan, ethtool, libvirt-python, netifaces
  Building wheel for koan (setup.py) ... done
  Created wheel for koan: filename=koan-2.9.0-py3-none-any.whl size=51724 sha256=21af52b161b6af4a41c1af556c882482fbfe5e4b4fbc759c4ff429358734beb7
  Stored in directory: /tmp/pip-ephem-wheel-cache-glb0z8yq/wheels/de/04/68/adfc75a7be69e46c5850caa92cee335cce584962e4e94b884d
  Building wheel for ethtool (setup.py) ... error
ERROR: Command errored out with exit status 1:
command: /home/dom/git/work/koan/koan/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_fep18l/ethtool/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j_fep18l/ethtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compil
e(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-b8j9cwy3      
       cwd: /tmp/pip-install-j_fep18l/ethtool/                                                                                                                                
  Complete output (5 lines):                                                           
  running bdist_wheel
  running build            
  running build_ext      
  building 'ethtool' extension
  Failed to query pkg-config --cflags-only-I libnl-3.0
  ----------------------------------------
  ERROR: Failed building wheel for ethtool
  Running setup.py clean for ethtool
  Building wheel for libvirt-python (setup.py) ... \done
  Created wheel for libvirt-python: filename=libvirt_python-6.7.0-cp38-cp38-linux_x86_64.whl size=563649 sha256=9dafd273fd8191fd761b8e5a9c0466b359f398a37618195775d7f847380d7c69
  Stored in directory: /home/dom/.cache/pip/wheels/da/7b/3a/99528db6aa9d79280536e28df7453a932ffca5daf7f29098fc
  Building wheel for netifaces (setup.py) ... done
  Created wheel for netifaces: filename=netifaces-0.10.9-cp38-cp38-linux_x86_64.whl size=36885 sha256=4499fa68b3520db6b1d0aa8a6151943cfad95e812ae79761f5d9ad7aa9463f7f
  Stored in directory: /home/dom/.cache/pip/wheels/9b/51/d5/d4682860392414da28ba3c5ffac0243983399b868a9cced6df
Successfully built koan libvirt-python netifaces
Failed to build ethtool
DEPRECATION: Could not build wheels for ethtool which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this fun
ctionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: simplejson, ethtool, distro, libvirt-python, netifaces, koan
    Running setup.py install for ethtool ... error
    ERROR: Command errored out with exit status 1:
     command: /home/dom/git/work/koan/koan/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_fep18l/ethtool/setup.py'"'"'; __file__='"
'"'/tmp/pip-install-j_fep18l/ethtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(comp
ile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-12ctznix/install-record.txt --single-version-externally-managed --compile --install-headers /home/dom/g
it/work/koan/koan/include/site/python3.8/ethtool
         cwd: /tmp/pip-install-j_fep18l/ethtool/
    Complete output (5 lines):
    running install
    running build
    running build_ext
    building 'ethtool' extension
    Failed to query pkg-config --cflags-only-I libnl-3.0
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/dom/git/work/koan/koan/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j_fep18l/e
thtool/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j_fep18l/ethtool/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', 
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-12ctznix/install-record.txt --single-version-externally-managed --comp
ile --install-headers /home/dom/git/work/koan/koan/include/site/python3.8/ethtool Check the logs for full command output.
```

When looking to the official [GitHub page](https://github.com/fedora-python/python-ethtool) of `ethtool` the maintainers recommend using [netifaces](https://pypi.org/project/netifaces) instead:

> This is the new upstream for python-ethtool maintained by Fedora's Python SIG. We ported it to Python 3 and only maintain it for the current tools to keep working. No new development is happening. This is a deprecated package. If you are considering to start using this, please don't. We recommend netifaces instead.

Koan has `netifaces` already as installation requirement, but still lists `ethtool`. When I remove this requirement the installation is successfull.

```shell
$ pip install .
Processing /home/dom/git/work/koan
Requirement already satisfied: simplejson in ./koan/lib64/python3.8/site-packages (from koan==2.9.0) (3.17.2)
Collecting distro
  Using cached distro-1.5.0-py2.py3-none-any.whl (18 kB)
Processing /home/dom/.cache/pip/wheels/da/7b/3a/99528db6aa9d79280536e28df7453a932ffca5daf7f29098fc/libvirt_python-6.7.0-cp38-cp38-linux_x86_64.whl
Processing /home/dom/.cache/pip/wheels/9b/51/d5/d4682860392414da28ba3c5ffac0243983399b868a9cced6df/netifaces-0.10.9-cp38-cp38-linux_x86_64.whl
Building wheels for collected packages: koan
  Building wheel for koan (setup.py) ... done
  Created wheel for koan: filename=koan-2.9.0-py3-none-any.whl size=51717 sha256=27c37c389ea0aa47d56405ec980902bd0888bb710fd4d961451d778ec703d63c
  Stored in directory: /tmp/pip-ephem-wheel-cache-jfectac_/wheels/de/04/68/adfc75a7be69e46c5850caa92cee335cce584962e4e94b884d
Successfully built koan
Installing collected packages: distro, libvirt-python, netifaces, koan
Successfully installed distro-1.5.0 koan-2.9.0 libvirt-python-6.7.0 netifaces-0.10.9
```

According to https://github.com/cobbler/koan/blob/f6f627299d060039e618846033c7cf74e3c9be6c/koan/utils.py#L33-L37 removing `ethtool`breaks the Python2 compatibility, though.

### PR DESCRIPTION
**Pull request by nodeg**
Removes old Python 2 code and fixes #66.

### CODE REVIEW

**Review by hbokh — COMMENTED** [review]
Unable to test this, since I've never used Koan in a proper way.
Judging the comment in #66 this seems legit.

**Review by SchoolGuy — CHANGES_REQUESTED** [review]
We need to adjust:

- The spec: https://github.com/cobbler/koan/blob/master/koan.spec#L98
- `setup.py`: https://github.com/cobbler/koan/blob/master/setup.py#L34

**Review by nodeg — COMMENTED** [review]
Changes applied!

**Review by SchoolGuy — APPROVED** [review]
LGTM now in my eyes

**Review by opoplawski — APPROVED** [review]
LGTM

**Pull request merged**
